apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: secret
  name: secret
  namespace: secretns102
spec:
  volumes:
  - name: shared-secret
    secret:
      secretName: consumable
  containers:
  - image: bitnami/nginx
    name: secret
    volumeMounts:
    - name: shared-secret
      readOnly: true
      mountPath: /var/src
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
