apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: tenants
  name: tenants
spec:
  volumes:
  - name: shared-vol
    emptyDir: {}
  containers:
  - args:
    - /bin/sh
    - -c
    - tail -f /dev/null
    image: alpine:latest
    name: ct100
    volumeMounts:
    - mountPath: /var/www/html
      name: shared-vol
  - args:
    - /bin/sh
    - -c
    - tail -f /dev/null
    image: alpine:latest
    name: cta150
    volumeMounts:
    - mountPath: /var/html
      name: shared-vol
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
