apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: frontend-python
  namespace: $INGRESS_NAMESPACE
spec:
  destination:
    server: 'https://kubernetes.default.svc'
  source:
    path: ./
    repoURL: $ARGO_REPO
    targetRevision: main
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: false