apiVersion: v1
kind: Secret
metadata:
  name: priv-repo-python-dev
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: $ARGO_REPO
  password: $GH_ADMIN
  username: $GITHUB_ORG